### PR TITLE
added babies data set

### PR DESCRIPTION
**Pull request by beanumber**
see issue #4 https://github.com/OpenIntroOrg/openintro-r-package/issues/4

### CODE REVIEW

**Comment by beanumber** [comment]
@OpenIntroOrg any thoughts on this?

**Comment by mine-cetinkaya-rundel** [comment]
Did the dataset in the pull request just come from the source files?

**Comment by beanumber** [comment]
Probably. Honestly it's been a while and I don't remember. :(

**Comment by mine-cetinkaya-rundel** [comment]
ok confirmed that that's it, merging. thanks!

**Pull request merged**
