### PR TITLE
New Datasets Added

### PR DESCRIPTION
**Pull request by npaterno**
New Datasets from the data_hunters project: major_earthquakes, mcu_films, salinity, sibling_heights, snowfall, ssd_speed

*Added data, data-raw, man and R files for each data set.
*Updated _pkgdown.yml and NEWS.md files top reflect the additions

Hi Mine, 

Please let me know if this process works for you (its one I vetted with David last month when I met with him). I've created a separate data_hunters package on my GitHub for that team to contribute to (currently just myself and one other member). It mirrors the openintro package organization (files, naming conventions, etc). Once there are enough new datasets there, I'm adding them to my forked openintro/usdata repository and then pull requesting to merge with openintro/usdata. That way you don't have to deal with multiple pull requests from everyone, there will just be one pull request coming from me. 

Hope you had a good end to your semester!

~Nick

### CODE REVIEW

**Review by mine-cetinkaya-rundel — CHANGES_REQUESTED** [review]
Thank you @npaterno for the new datasets. These are looking great. I pushed a few edits but would love your input on a few more changes to make. 

- `snowfall`: It's confusing that the main variable and the dataset has the same name. Could we change one of them? I thought about making the dataset be called `mtrainier` but that's not super easy to spell if you don't know that mountain. 
- `major_earthquakes`: Is there a publicly available data source we can link? Also, is there a definition of what "major earthquake" means that we can add to the docs? I'm finding https://www.infoplease.com/askeds/major-earthquakes which suggests >7 but this dataset goes down to 5.5. Finally, are these intensities or magnitudes? I thought richter measures magnitude not intensity, and then in the description, the word "strength" is used and I *think* these all mean different things. Clarifying this could help reduce the length of the variable name too.
- `mcu_films`: Can you add a bit more detail (maybe just another sentence) to the description so it's meaningful to someone who doesn't know what the Infinity saga is. Also, since there is $ amounts as well as all-time gross, it would be useful to indicate year when these data are as of. Are $ amounts in adjusted to that year or not? Were these harvested from individual pages or from a single list on IMDB -- if the latter, we can link to that in the source. Finally, why is the rating removed in the data prep? Happy to leave it out if you think that's more appropriate but I wasn't sure.
- `sibling_heights`: Was there a particular use case suggested for this dataset? I'm not too keen on adding more datasets by Pearson, Fisher, etc. but curious what the motivation was and if there is a specific use case in mind, maybe we can find something like it from another (more recent) data source?

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel 

Thanks for making those edits! I will review them in detail to make sure I have things formatted better in future pull requests. 

snowfall: I'll change the variable name for this dataset. 

major_earthquakes: The Richter is a magnitude measurement; I'll adjust the description for that. I'll see if I can find how the publisher defined "major" earthquake. If I can't find anything maybe we change the dataset name to something like "notable_earthquakes". I'm not aware of a publicly available link but will look for one. I have a pdf of the book and used that as the source. 

mcu_films: I'll add to the description to be more meaningful. I don't believe the $ amounts are adjusted but I will look into it to confirm. Data was pulled from individual pages for each film. Rating was only removed since the value is the same for every film in the dataset. 

sibling_heights: I knew about Fisher but somehow missed Pearson's views on eugenics. I am 100% ok with removing this dataset and replacing it with another; the intended use was for regression/correlation.

**Comment by mine-cetinkaya-rundel** [comment]
@npaterno I think one consistent change I made was explicitly using `x` and `y` arguments in `aes()` of ggplots. Thank you!

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel 

Changes in the last comment are complete. 

snowfall: I changed variable to "total_snow".

major_earthquakes: I was unable to find what definition the publisher was using but other definitions I did find match what you found so I changed the dataset name to just "earthquakes" and changed the description in documentation to be "notable" instead of "major". The "intensity_richter" was changed to "richter" and description now reads "magnitude" instead of "strength". I was not able to find a publicly available data source.

mcu_films: I added a line to the description to give a quick definition of the Infinity saga. I also added a note to explain the box office values; IMDB does not adjust to a specific year so the $ amounts are from the year the film was released. 

sibling_heights: This dataset has been removed and will be replaced with a different one in the next pull request.

devtools::check() is passing and all four R-CMD-checks are passing on GitHub.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @npaterno! I think the only remaining question I have is on `mcu_films`. `gross_us` and `gross_world` seem to be "all time" numbers, right? If so, are they as of the data collection date? Could we add that date to the documentation? Saying something along the lines of "data were collected from IMDB on ___"?

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel 

The `gross_us` and `gross_world` are "all time" values but box office values only count ticket sales from theatrical runs. So once the movies are out of theatres, that amount does not change (so all of these are now fixed values).

Semi-related side note: I've been using the OpenIntro text and following you on twitter for a few years and I admit I have been geeking out a bit that I get to work with you on this project now.

**Comment by mine-cetinkaya-rundel** [comment]
😄 

Ah, that makes sense! Alright, this is good to go then! Thank you so much!

**Review by mine-cetinkaya-rundel — APPROVED** [review]

**Pull request merged**
