### PR TITLE
Fix typos for `race_justice` data set and documentation

### PR DESCRIPTION
**Pull request by DavidDiez**
For these updates, I'm referencing the top-right of page 23 of the [source PDF](https://docs.cdn.yougov.com/s23agrrx47/20200531_yahoo_race_and_justice_crosstabs.pdf).

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Review by npaterno — CHANGES_REQUESTED** [review]
Thanks for catching the typo in race_justice! 

It looks like the new data set isn't documented yet. Can you run devtools::document() so the man file is generated? I believe that's what is stopping the R CMD checks from passing.

**Comment by mine-cetinkaya-rundel** [comment]
@DavidDiez There is a very nice (and continuously updated) package called [coronavirus](https://ramikrispin.github.io/coronavirus/) that this sort of data can be pulled from. How about using that in any exercises instead of recording data here that will soon be out of date?

**Comment by DavidDiez** [comment]
Sure, I can take a look at that package to see if it has what I will need for that future update. The data set that I had added was intended for the future anyways (didn't even realize it was included in the pull request when I made it) and already removed.

Any idea what to do on this warning?

> Warning:   LazyData DB of 5.2 MB without LazyDataCompression set

**Comment by mine-cetinkaya-rundel** [comment]
That's related to what I mentioned re: new CRAN submission needed.

So if we're ready to wrap up this PR I'll get to working on that. Don't worry about that warning for now.

**Comment by DavidDiez** [comment]
Yep, this PR doesn't have any other planned changes. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
@npaterno Do you have an objection to naming the sample size column in `race_justice` just `n`, and noting in the documentation that it's unweighted? Sample weighting doesn't come up in the intro curriculum, so the naming (if dataset is used in class) would require introducing a new concept. I can make the change (in the midst of making a couple other changes to docs anyway).

**Comment by mine-cetinkaya-rundel** [comment]
Actually, ignore my comment above. I'm going to make the dataset into raw data, I didn't realize before that it was basically a contingency table. We should include data where each row is an observation from the study the data comes from, where possible.

**Pull request merged**
