### PR TITLE
adding births14 data

### PR DESCRIPTION
**Pull request by AmeliaMN**
This is related to #4, adding a more updated version of the `ncbirths` dataset with better data provenance. I've included the data-cleaning code I used to make the small sample, but not the original raw datasets, as they are very large. I'm not sure if this will be a problem when compiling the package, but I'm hopeful this PR is useful.

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
@AmeliaMN -- Thank you for this! How big was the original file? I can't locate the exact file on the webpage you linked to (I'm sure I'm missing some step!), could you either point me to it or add it to the PR in the `data-raw` directory? The size of files in there don't matter since they don't end up being part of the package. If it's greater than 100MB that would be an issue with GitHub though so if that's the case pointing to the original source would be sufficient.

**Comment by AmeliaMN** [comment]
The original data file is huge (2 GB) so I didn't commit it. It is available through the DOI I linked on the documentation page, https://doi.org/10.3886/ICPSR36461.v1 there's a "Download" button with a dropdown that will download a zip file with the data.

**Comment by mine-cetinkaya-rundel** [comment]
When I download from that link I only get the documentation and not the data file in the zipped folder that's downloaded, that's why I was confused. Any idea what step I might be missing?

**Comment by AmeliaMN** [comment]
Maybe you're just clicking, without getting the dropdown part? Or perhaps you need to be logged in? Here's what it looks like to me: 
Screen Shot 2021-01-03 at 5 49 47 PM

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Pull request merged**
