### PR TITLE
updating a few datasets

### PR DESCRIPTION
**Pull request by hardin47**
Added 

* pm 2.5, Durham 2022
* paralympic & olympic 1500

Updated NYC marathon

### CODE REVIEW

**Comment by hardin47** [comment]
for the climate data, i added a map to the examples.  is that cool?  i can add a different example if you prefer.

**Comment by mine-cetinkaya-rundel** [comment]
I don't know why one of the actions keep failing but the rest are ok and check passes locally so I'm going to merge this!

**Comment by hardin47** [comment]
sorry, i found a typo in the paralympic dataset!

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 No problem, you can make another PR with the update

**Pull request merged**
